frr version 8.4_git
frr defaults traditional
hostname edge1
domainname localdomain
log syslog informational
no ip forwarding
ipv6 forwarding
!
interface eth0
 ipv6 address fd00:12::/127
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
exit
!
interface gre-netclaw
 ipv6 address fd00:ee::/127
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
exit
!
interface lo
 ipv6 address fd00::1/128
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
exit
!
router bgp 65000
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor fd00::2 remote-as 65000
 neighbor fd00::2 description core-rr
 neighbor fd00::2 update-source lo
 neighbor fd00:ee::1 remote-as 65001
 neighbor fd00:ee::1 description wsl-netclaw
 !
 address-family ipv6 unicast
  network fd00::1/128
  network fd00:12::/127
  network fd00:ee::/127
  neighbor fd00::2 activate
  neighbor fd00::2 next-hop-self
  neighbor fd00:ee::1 activate
 exit-address-family
exit
!
router ospf6
 ospf6 router-id 1.1.1.1
exit
!
end
